#!/usr/bin/perl
use strict;

my $scan = `iwlist wlan0 scan`;
my @cells = ($scan =~ /^(          Cell \d(?:[^\n]|\n                    )*)/mg);
@cells = map {
    my $cell = {};
    if (/Address: ([0-9a-zA-Z:]*)/) {
        $cell->{address} = $1;
    }
    else {
        warn "No address found\n";
    }
    if (/ESSID:"([^"]*)"/) {
        $cell->{essid} = $1;
    }
    else {
        warn "No essid found\n";
    }
    if (/Quality=(\d+\/\d+)/) {
        $cell->{quality} = $1;
    }
    else {
        warn "No quality found\n";
    }
    if (/Signal level=(\d+\/\d+)/) {
        $cell->{signal_level} = $1;
    }
    else {
        warn "No signal level found\n";
    }
    $cell;
} @cells;

print "[";
for my $i (0..$#cells) {
    print "{address:\"$cells[$i]{address}\",essid:\"$cells[$i]{essid}\",quality:\"$cells[$i]{quality}\",signal_level:\"$cells[$i]{signal_level}\"}";
    print "," unless $i == $#cells;
}
print "]\n";
